// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/prod/prod_service.proto

package pb_prod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Sku           int64                  `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_prod_prod_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prod_prod_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_prod_prod_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetProductRequest) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

//
type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_api_prod_prod_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_prod_prod_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_api_prod_prod_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_api_prod_prod_service_proto protoreflect.FileDescriptor

const file_api_prod_prod_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/prod/prod_service.proto\x12\x10route256.product\";\n" +
	"\x11GetProductRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\x03R\x03sku\">\n" +
	"\x12GetProductResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price2k\n" +
	"\x0eProductService\x12Y\n" +
	"\n" +
	"GetProduct\x12#.route256.product.GetProductRequest\x1a$.route256.product.GetProductResponse\"\x00B!Z\x1froute/cart/pkg/api/prod;pb_prodb\x06proto3"

var (
	file_api_prod_prod_service_proto_rawDescOnce sync.Once
	file_api_prod_prod_service_proto_rawDescData []byte
)

func file_api_prod_prod_service_proto_rawDescGZIP() []byte {
	file_api_prod_prod_service_proto_rawDescOnce.Do(func() {
		file_api_prod_prod_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_prod_prod_service_proto_rawDesc), len(file_api_prod_prod_service_proto_rawDesc)))
	})
	return file_api_prod_prod_service_proto_rawDescData
}

var file_api_prod_prod_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_prod_prod_service_proto_goTypes = []any{
	(*GetProductRequest)(nil),  // 0: route256.product.GetProductRequest
	(*GetProductResponse)(nil), // 1: route256.product.GetProductResponse
}
var file_api_prod_prod_service_proto_depIdxs = []int32{
	0, // 0: route256.product.ProductService.GetProduct:input_type -> route256.product.GetProductRequest
	1, // 1: route256.product.ProductService.GetProduct:output_type -> route256.product.GetProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_prod_prod_service_proto_init() }
func file_api_prod_prod_service_proto_init() {
	if File_api_prod_prod_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_prod_prod_service_proto_rawDesc), len(file_api_prod_prod_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_prod_prod_service_proto_goTypes,
		DependencyIndexes: file_api_prod_prod_service_proto_depIdxs,
		MessageInfos:      file_api_prod_prod_service_proto_msgTypes,
	}.Build()
	File_api_prod_prod_service_proto = out.File
	file_api_prod_prod_service_proto_goTypes = nil
	file_api_prod_prod_service_proto_depIdxs = nil
}
