// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/loms_service.proto

package pb_loms

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type OrderStatus int32

const (
	OrderStatus_UNKNOWN          OrderStatus = 0
	OrderStatus_NEW              OrderStatus = 1
	OrderStatus_AWAITING_PAYMENT OrderStatus = 2
	OrderStatus_FAILED           OrderStatus = 3
	OrderStatus_PAYED            OrderStatus = 4
	OrderStatus_CANCELLED        OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "NEW",
		2: "AWAITING_PAYMENT",
		3: "FAILED",
		4: "PAYED",
		5: "CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"UNKNOWN":          0,
		"NEW":              1,
		"AWAITING_PAYMENT": 2,
		"FAILED":           3,
		"PAYED":            4,
		"CANCELLED":        5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_loms_service_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_v1_loms_service_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{0}
}

//===========================
//
type OrderCreateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	User          uint64                     `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Items         []*OrderCreateRequest_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateRequest) Reset() {
	*x = OrderCreateRequest{}
	mi := &file_api_v1_loms_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest) ProtoMessage() {}

func (x *OrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreateRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *OrderCreateRequest) GetItems() []*OrderCreateRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

//
type OrderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResponse) Reset() {
	*x = OrderCreateResponse{}
	mi := &file_api_v1_loms_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResponse) ProtoMessage() {}

func (x *OrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreateResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

//===========================
//
type OrderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoRequest) Reset() {
	*x = OrderInfoRequest{}
	mi := &file_api_v1_loms_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoRequest) ProtoMessage() {}

func (x *OrderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoRequest.ProtoReflect.Descriptor instead.
func (*OrderInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{2}
}

func (x *OrderInfoRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

//
type OrderInfoResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        OrderStatus               `protobuf:"varint,1,opt,name=status,proto3,enum=route.loms.pkg.api.v1.OrderStatus" json:"status,omitempty"`
	User          uint64                    `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Items         []*OrderInfoResponse_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_api_v1_loms_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{3}
}

func (x *OrderInfoResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNKNOWN
}

func (x *OrderInfoResponse) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *OrderInfoResponse) GetItems() []*OrderInfoResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

//===========================
//
type OrderPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayRequest) Reset() {
	*x = OrderPayRequest{}
	mi := &file_api_v1_loms_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayRequest) ProtoMessage() {}

func (x *OrderPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayRequest.ProtoReflect.Descriptor instead.
func (*OrderPayRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{4}
}

func (x *OrderPayRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

//
type OrderPayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayResponse) Reset() {
	*x = OrderPayResponse{}
	mi := &file_api_v1_loms_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResponse) ProtoMessage() {}

func (x *OrderPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResponse.ProtoReflect.Descriptor instead.
func (*OrderPayResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{5}
}

//===========================
//
type OrderCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelRequest) Reset() {
	*x = OrderCancelRequest{}
	mi := &file_api_v1_loms_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelRequest) ProtoMessage() {}

func (x *OrderCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelRequest.ProtoReflect.Descriptor instead.
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{6}
}

func (x *OrderCancelRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

//
type OrderCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelResponse) Reset() {
	*x = OrderCancelResponse{}
	mi := &file_api_v1_loms_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelResponse) ProtoMessage() {}

func (x *OrderCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelResponse.ProtoReflect.Descriptor instead.
func (*OrderCancelResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{7}
}

//===========================
//
type StockInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoRequest) Reset() {
	*x = StockInfoRequest{}
	mi := &file_api_v1_loms_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoRequest) ProtoMessage() {}

func (x *StockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoRequest.ProtoReflect.Descriptor instead.
func (*StockInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{8}
}

func (x *StockInfoRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

//
type StockInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoResponse) Reset() {
	*x = StockInfoResponse{}
	mi := &file_api_v1_loms_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoResponse) ProtoMessage() {}

func (x *StockInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoResponse.ProtoReflect.Descriptor instead.
func (*StockInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{9}
}

func (x *StockInfoResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderCreateRequest_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateRequest_Item) Reset() {
	*x = OrderCreateRequest_Item{}
	mi := &file_api_v1_loms_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest_Item) ProtoMessage() {}

func (x *OrderCreateRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest_Item.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest_Item) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OrderCreateRequest_Item) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *OrderCreateRequest_Item) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderInfoResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfoResponse_Item) Reset() {
	*x = OrderInfoResponse_Item{}
	mi := &file_api_v1_loms_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse_Item) ProtoMessage() {}

func (x *OrderInfoResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_loms_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse_Item.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse_Item) Descriptor() ([]byte, []int) {
	return file_api_v1_loms_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *OrderInfoResponse_Item) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *OrderInfoResponse_Item) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_v1_loms_service_proto protoreflect.FileDescriptor

const file_api_v1_loms_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/v1/loms_service.proto\x12\x15route.loms.pkg.api.v1\x1a\x1cgoogle/api/annotations.proto\"\x9e\x01\n" +
	"\x12OrderCreateRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12D\n" +
	"\x05items\x18\x02 \x03(\v2..route.loms.pkg.api.v1.OrderCreateRequest.ItemR\x05items\x1a.\n" +
	"\x04Item\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"0\n" +
	"\x13OrderCreateResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"-\n" +
	"\x10OrderInfoRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"\xd8\x01\n" +
	"\x11OrderInfoResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".route.loms.pkg.api.v1.OrderStatusR\x06status\x12\x12\n" +
	"\x04user\x18\x02 \x01(\x04R\x04user\x12C\n" +
	"\x05items\x18\x03 \x03(\v2-.route.loms.pkg.api.v1.OrderInfoResponse.ItemR\x05items\x1a.\n" +
	"\x04Item\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\",\n" +
	"\x0fOrderPayRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"\x12\n" +
	"\x10OrderPayResponse\"/\n" +
	"\x12OrderCancelRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"\x15\n" +
	"\x13OrderCancelResponse\"$\n" +
	"\x10StockInfoRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\")\n" +
	"\x11StockInfoResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count*_\n" +
	"\vOrderStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\x14\n" +
	"\x10AWAITING_PAYMENT\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\t\n" +
	"\x05PAYED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\xea\x04\n" +
	"\x04Loms\x12~\n" +
	"\vOrderCreate\x12).route.loms.pkg.api.v1.OrderCreateRequest\x1a*.route.loms.pkg.api.v1.OrderCreateResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/order/create\x12v\n" +
	"\tOrderInfo\x12'.route.loms.pkg.api.v1.OrderInfoRequest\x1a(.route.loms.pkg.api.v1.OrderInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/order/info\x12r\n" +
	"\bOrderPay\x12&.route.loms.pkg.api.v1.OrderPayRequest\x1a'.route.loms.pkg.api.v1.OrderPayResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/order/pay\x12~\n" +
	"\vOrderCancel\x12).route.loms.pkg.api.v1.OrderCancelRequest\x1a*.route.loms.pkg.api.v1.OrderCancelResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/order/cancel\x12v\n" +
	"\tStockInfo\x12'.route.loms.pkg.api.v1.StockInfoRequest\x1a(.route.loms.pkg.api.v1.StockInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/stock/infoB\x1fZ\x1droute/loms/pkg/api/v1;pb_lomsb\x06proto3"

var (
	file_api_v1_loms_service_proto_rawDescOnce sync.Once
	file_api_v1_loms_service_proto_rawDescData []byte
)

func file_api_v1_loms_service_proto_rawDescGZIP() []byte {
	file_api_v1_loms_service_proto_rawDescOnce.Do(func() {
		file_api_v1_loms_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_loms_service_proto_rawDesc), len(file_api_v1_loms_service_proto_rawDesc)))
	})
	return file_api_v1_loms_service_proto_rawDescData
}

var file_api_v1_loms_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_loms_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1_loms_service_proto_goTypes = []any{
	(OrderStatus)(0),                // 0: route.loms.pkg.api.v1.OrderStatus
	(*OrderCreateRequest)(nil),      // 1: route.loms.pkg.api.v1.OrderCreateRequest
	(*OrderCreateResponse)(nil),     // 2: route.loms.pkg.api.v1.OrderCreateResponse
	(*OrderInfoRequest)(nil),        // 3: route.loms.pkg.api.v1.OrderInfoRequest
	(*OrderInfoResponse)(nil),       // 4: route.loms.pkg.api.v1.OrderInfoResponse
	(*OrderPayRequest)(nil),         // 5: route.loms.pkg.api.v1.OrderPayRequest
	(*OrderPayResponse)(nil),        // 6: route.loms.pkg.api.v1.OrderPayResponse
	(*OrderCancelRequest)(nil),      // 7: route.loms.pkg.api.v1.OrderCancelRequest
	(*OrderCancelResponse)(nil),     // 8: route.loms.pkg.api.v1.OrderCancelResponse
	(*StockInfoRequest)(nil),        // 9: route.loms.pkg.api.v1.StockInfoRequest
	(*StockInfoResponse)(nil),       // 10: route.loms.pkg.api.v1.StockInfoResponse
	(*OrderCreateRequest_Item)(nil), // 11: route.loms.pkg.api.v1.OrderCreateRequest.Item
	(*OrderInfoResponse_Item)(nil),  // 12: route.loms.pkg.api.v1.OrderInfoResponse.Item
}
var file_api_v1_loms_service_proto_depIdxs = []int32{
	11, // 0: route.loms.pkg.api.v1.OrderCreateRequest.items:type_name -> route.loms.pkg.api.v1.OrderCreateRequest.Item
	0,  // 1: route.loms.pkg.api.v1.OrderInfoResponse.status:type_name -> route.loms.pkg.api.v1.OrderStatus
	12, // 2: route.loms.pkg.api.v1.OrderInfoResponse.items:type_name -> route.loms.pkg.api.v1.OrderInfoResponse.Item
	1,  // 3: route.loms.pkg.api.v1.Loms.OrderCreate:input_type -> route.loms.pkg.api.v1.OrderCreateRequest
	3,  // 4: route.loms.pkg.api.v1.Loms.OrderInfo:input_type -> route.loms.pkg.api.v1.OrderInfoRequest
	5,  // 5: route.loms.pkg.api.v1.Loms.OrderPay:input_type -> route.loms.pkg.api.v1.OrderPayRequest
	7,  // 6: route.loms.pkg.api.v1.Loms.OrderCancel:input_type -> route.loms.pkg.api.v1.OrderCancelRequest
	9,  // 7: route.loms.pkg.api.v1.Loms.StockInfo:input_type -> route.loms.pkg.api.v1.StockInfoRequest
	2,  // 8: route.loms.pkg.api.v1.Loms.OrderCreate:output_type -> route.loms.pkg.api.v1.OrderCreateResponse
	4,  // 9: route.loms.pkg.api.v1.Loms.OrderInfo:output_type -> route.loms.pkg.api.v1.OrderInfoResponse
	6,  // 10: route.loms.pkg.api.v1.Loms.OrderPay:output_type -> route.loms.pkg.api.v1.OrderPayResponse
	8,  // 11: route.loms.pkg.api.v1.Loms.OrderCancel:output_type -> route.loms.pkg.api.v1.OrderCancelResponse
	10, // 12: route.loms.pkg.api.v1.Loms.StockInfo:output_type -> route.loms.pkg.api.v1.StockInfoResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_loms_service_proto_init() }
func file_api_v1_loms_service_proto_init() {
	if File_api_v1_loms_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_loms_service_proto_rawDesc), len(file_api_v1_loms_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_loms_service_proto_goTypes,
		DependencyIndexes: file_api_v1_loms_service_proto_depIdxs,
		EnumInfos:         file_api_v1_loms_service_proto_enumTypes,
		MessageInfos:      file_api_v1_loms_service_proto_msgTypes,
	}.Build()
	File_api_v1_loms_service_proto = out.File
	file_api_v1_loms_service_proto_goTypes = nil
	file_api_v1_loms_service_proto_depIdxs = nil
}
