// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/v1/cart_service.proto

package pb_cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cart_CartItemAdd_FullMethodName    = "/route.cart.pkg.api.v1.Cart/CartItemAdd"
	Cart_CartItemDelete_FullMethodName = "/route.cart.pkg.api.v1.Cart/CartItemDelete"
	Cart_CartList_FullMethodName       = "/route.cart.pkg.api.v1.Cart/CartList"
	Cart_CartClear_FullMethodName      = "/route.cart.pkg.api.v1.Cart/CartClear"
	Cart_CartCheckout_FullMethodName   = "/route.cart.pkg.api.v1.Cart/CartCheckout"
)

// CartClient is the client API for Cart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartClient interface {
	//
	CartItemAdd(ctx context.Context, in *CartItemAddRequest, opts ...grpc.CallOption) (*CartItemAddResponse, error)
	//
	CartItemDelete(ctx context.Context, in *CartItemDeleteRequest, opts ...grpc.CallOption) (*CartItemDeleteResponse, error)
	//
	CartList(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*CartListResponse, error)
	//
	CartClear(ctx context.Context, in *CartClearRequest, opts ...grpc.CallOption) (*CartClearResponse, error)
	//
	CartCheckout(ctx context.Context, in *CartCheckoutRequest, opts ...grpc.CallOption) (*CartCheckoutResponse, error)
}

type cartClient struct {
	cc grpc.ClientConnInterface
}

func NewCartClient(cc grpc.ClientConnInterface) CartClient {
	return &cartClient{cc}
}

func (c *cartClient) CartItemAdd(ctx context.Context, in *CartItemAddRequest, opts ...grpc.CallOption) (*CartItemAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemAddResponse)
	err := c.cc.Invoke(ctx, Cart_CartItemAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) CartItemDelete(ctx context.Context, in *CartItemDeleteRequest, opts ...grpc.CallOption) (*CartItemDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemDeleteResponse)
	err := c.cc.Invoke(ctx, Cart_CartItemDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) CartList(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*CartListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartListResponse)
	err := c.cc.Invoke(ctx, Cart_CartList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) CartClear(ctx context.Context, in *CartClearRequest, opts ...grpc.CallOption) (*CartClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartClearResponse)
	err := c.cc.Invoke(ctx, Cart_CartClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) CartCheckout(ctx context.Context, in *CartCheckoutRequest, opts ...grpc.CallOption) (*CartCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartCheckoutResponse)
	err := c.cc.Invoke(ctx, Cart_CartCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServer is the server API for Cart service.
// All implementations must embed UnimplementedCartServer
// for forward compatibility.
type CartServer interface {
	//
	CartItemAdd(context.Context, *CartItemAddRequest) (*CartItemAddResponse, error)
	//
	CartItemDelete(context.Context, *CartItemDeleteRequest) (*CartItemDeleteResponse, error)
	//
	CartList(context.Context, *CartListRequest) (*CartListResponse, error)
	//
	CartClear(context.Context, *CartClearRequest) (*CartClearResponse, error)
	//
	CartCheckout(context.Context, *CartCheckoutRequest) (*CartCheckoutResponse, error)
	mustEmbedUnimplementedCartServer()
}

// UnimplementedCartServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartServer struct{}

func (UnimplementedCartServer) CartItemAdd(context.Context, *CartItemAddRequest) (*CartItemAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CartItemAdd not implemented")
}
func (UnimplementedCartServer) CartItemDelete(context.Context, *CartItemDeleteRequest) (*CartItemDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CartItemDelete not implemented")
}
func (UnimplementedCartServer) CartList(context.Context, *CartListRequest) (*CartListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CartList not implemented")
}
func (UnimplementedCartServer) CartClear(context.Context, *CartClearRequest) (*CartClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CartClear not implemented")
}
func (UnimplementedCartServer) CartCheckout(context.Context, *CartCheckoutRequest) (*CartCheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CartCheckout not implemented")
}
func (UnimplementedCartServer) mustEmbedUnimplementedCartServer() {}
func (UnimplementedCartServer) testEmbeddedByValue()              {}

// UnsafeCartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServer will
// result in compilation errors.
type UnsafeCartServer interface {
	mustEmbedUnimplementedCartServer()
}

func RegisterCartServer(s grpc.ServiceRegistrar, srv CartServer) {
	// If the following call panics, it indicates UnimplementedCartServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cart_ServiceDesc, srv)
}

func _Cart_CartItemAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItemAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).CartItemAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_CartItemAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).CartItemAdd(ctx, req.(*CartItemAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_CartItemDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItemDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).CartItemDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_CartItemDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).CartItemDelete(ctx, req.(*CartItemDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_CartList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).CartList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_CartList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).CartList(ctx, req.(*CartListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_CartClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).CartClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_CartClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).CartClear(ctx, req.(*CartClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_CartCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).CartCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_CartCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).CartCheckout(ctx, req.(*CartCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cart_ServiceDesc is the grpc.ServiceDesc for Cart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "route.cart.pkg.api.v1.Cart",
	HandlerType: (*CartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CartItemAdd",
			Handler:    _Cart_CartItemAdd_Handler,
		},
		{
			MethodName: "CartItemDelete",
			Handler:    _Cart_CartItemDelete_Handler,
		},
		{
			MethodName: "CartList",
			Handler:    _Cart_CartList_Handler,
		},
		{
			MethodName: "CartClear",
			Handler:    _Cart_CartClear_Handler,
		},
		{
			MethodName: "CartCheckout",
			Handler:    _Cart_CartCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/cart_service.proto",
}
