// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/cart_service.proto

package pb_cart

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//===========================
//
type CartItemAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemAddRequest) Reset() {
	*x = CartItemAddRequest{}
	mi := &file_api_v1_cart_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemAddRequest) ProtoMessage() {}

func (x *CartItemAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemAddRequest.ProtoReflect.Descriptor instead.
func (*CartItemAddRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{0}
}

func (x *CartItemAddRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CartItemAddRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *CartItemAddRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//
type CartItemAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemAddResponse) Reset() {
	*x = CartItemAddResponse{}
	mi := &file_api_v1_cart_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemAddResponse) ProtoMessage() {}

func (x *CartItemAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemAddResponse.ProtoReflect.Descriptor instead.
func (*CartItemAddResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{1}
}

//===========================
//
type CartItemDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Sku           uint32                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemDeleteRequest) Reset() {
	*x = CartItemDeleteRequest{}
	mi := &file_api_v1_cart_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemDeleteRequest) ProtoMessage() {}

func (x *CartItemDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemDeleteRequest.ProtoReflect.Descriptor instead.
func (*CartItemDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{2}
}

func (x *CartItemDeleteRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CartItemDeleteRequest) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

//
type CartItemDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemDeleteResponse) Reset() {
	*x = CartItemDeleteResponse{}
	mi := &file_api_v1_cart_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemDeleteResponse) ProtoMessage() {}

func (x *CartItemDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemDeleteResponse.ProtoReflect.Descriptor instead.
func (*CartItemDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{3}
}

//===========================
//
type CartListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListRequest) Reset() {
	*x = CartListRequest{}
	mi := &file_api_v1_cart_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListRequest) ProtoMessage() {}

func (x *CartListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListRequest.ProtoReflect.Descriptor instead.
func (*CartListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{4}
}

func (x *CartListRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

//
type CartListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*CartListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    uint32                   `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListResponse) Reset() {
	*x = CartListResponse{}
	mi := &file_api_v1_cart_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListResponse) ProtoMessage() {}

func (x *CartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListResponse.ProtoReflect.Descriptor instead.
func (*CartListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{5}
}

func (x *CartListResponse) GetItems() []*CartListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartListResponse) GetTotalPrice() uint32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

//===========================
//
type CartClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartClearRequest) Reset() {
	*x = CartClearRequest{}
	mi := &file_api_v1_cart_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartClearRequest) ProtoMessage() {}

func (x *CartClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartClearRequest.ProtoReflect.Descriptor instead.
func (*CartClearRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{6}
}

func (x *CartClearRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

//
type CartClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartClearResponse) Reset() {
	*x = CartClearResponse{}
	mi := &file_api_v1_cart_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartClearResponse) ProtoMessage() {}

func (x *CartClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartClearResponse.ProtoReflect.Descriptor instead.
func (*CartClearResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{7}
}

//===========================
//
type CartCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartCheckoutRequest) Reset() {
	*x = CartCheckoutRequest{}
	mi := &file_api_v1_cart_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartCheckoutRequest) ProtoMessage() {}

func (x *CartCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartCheckoutRequest.ProtoReflect.Descriptor instead.
func (*CartCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{8}
}

func (x *CartCheckoutRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

//
type CartCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartCheckoutResponse) Reset() {
	*x = CartCheckoutResponse{}
	mi := &file_api_v1_cart_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartCheckoutResponse) ProtoMessage() {}

func (x *CartCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartCheckoutResponse.ProtoReflect.Descriptor instead.
func (*CartCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{9}
}

func (x *CartCheckoutResponse) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CartListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint32                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListResponse_Item) Reset() {
	*x = CartListResponse_Item{}
	mi := &file_api_v1_cart_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListResponse_Item) ProtoMessage() {}

func (x *CartListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_cart_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListResponse_Item.ProtoReflect.Descriptor instead.
func (*CartListResponse_Item) Descriptor() ([]byte, []int) {
	return file_api_v1_cart_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CartListResponse_Item) GetSku() uint32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *CartListResponse_Item) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartListResponse_Item) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_api_v1_cart_service_proto protoreflect.FileDescriptor

const file_api_v1_cart_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/v1/cart_service.proto\x12\x15route.cart.pkg.api.v1\x1a\x1cgoogle/api/annotations.proto\"P\n" +
	"\x12CartItemAddRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\x15\n" +
	"\x13CartItemAddResponse\"=\n" +
	"\x15CartItemDeleteRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\rR\x03sku\"\x18\n" +
	"\x16CartItemDeleteResponse\"%\n" +
	"\x0fCartListRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\"\xd1\x01\n" +
	"\x10CartListResponse\x12B\n" +
	"\x05items\x18\x01 \x03(\v2,.route.cart.pkg.api.v1.CartListResponse.ItemR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\rR\n" +
	"totalPrice\x1aX\n" +
	"\x04Item\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\rR\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\"&\n" +
	"\x10CartClearRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\"\x13\n" +
	"\x11CartClearResponse\")\n" +
	"\x13CartCheckoutRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\"1\n" +
	"\x14CartCheckoutResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId2\x86\x05\n" +
	"\x04Cart\x12\x7f\n" +
	"\vCartItemAdd\x12).route.cart.pkg.api.v1.CartItemAddRequest\x1a*.route.cart.pkg.api.v1.CartItemAddResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/cart/item/add\x12\x8b\x01\n" +
	"\x0eCartItemDelete\x12,.route.cart.pkg.api.v1.CartItemDeleteRequest\x1a-.route.cart.pkg.api.v1.CartItemDeleteResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/cart/item/delete\x12r\n" +
	"\bCartList\x12&.route.cart.pkg.api.v1.CartListRequest\x1a'.route.cart.pkg.api.v1.CartListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/cart/list\x12v\n" +
	"\tCartClear\x12'.route.cart.pkg.api.v1.CartClearRequest\x1a(.route.cart.pkg.api.v1.CartClearResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/cart/clear\x12\x82\x01\n" +
	"\fCartCheckout\x12*.route.cart.pkg.api.v1.CartCheckoutRequest\x1a+.route.cart.pkg.api.v1.CartCheckoutResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/cart/checkoutB\x1fZ\x1droute/cart/pkg/api/v1;pb_cartb\x06proto3"

var (
	file_api_v1_cart_service_proto_rawDescOnce sync.Once
	file_api_v1_cart_service_proto_rawDescData []byte
)

func file_api_v1_cart_service_proto_rawDescGZIP() []byte {
	file_api_v1_cart_service_proto_rawDescOnce.Do(func() {
		file_api_v1_cart_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_cart_service_proto_rawDesc), len(file_api_v1_cart_service_proto_rawDesc)))
	})
	return file_api_v1_cart_service_proto_rawDescData
}

var file_api_v1_cart_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_cart_service_proto_goTypes = []any{
	(*CartItemAddRequest)(nil),     // 0: route.cart.pkg.api.v1.CartItemAddRequest
	(*CartItemAddResponse)(nil),    // 1: route.cart.pkg.api.v1.CartItemAddResponse
	(*CartItemDeleteRequest)(nil),  // 2: route.cart.pkg.api.v1.CartItemDeleteRequest
	(*CartItemDeleteResponse)(nil), // 3: route.cart.pkg.api.v1.CartItemDeleteResponse
	(*CartListRequest)(nil),        // 4: route.cart.pkg.api.v1.CartListRequest
	(*CartListResponse)(nil),       // 5: route.cart.pkg.api.v1.CartListResponse
	(*CartClearRequest)(nil),       // 6: route.cart.pkg.api.v1.CartClearRequest
	(*CartClearResponse)(nil),      // 7: route.cart.pkg.api.v1.CartClearResponse
	(*CartCheckoutRequest)(nil),    // 8: route.cart.pkg.api.v1.CartCheckoutRequest
	(*CartCheckoutResponse)(nil),   // 9: route.cart.pkg.api.v1.CartCheckoutResponse
	(*CartListResponse_Item)(nil),  // 10: route.cart.pkg.api.v1.CartListResponse.Item
}
var file_api_v1_cart_service_proto_depIdxs = []int32{
	10, // 0: route.cart.pkg.api.v1.CartListResponse.items:type_name -> route.cart.pkg.api.v1.CartListResponse.Item
	0,  // 1: route.cart.pkg.api.v1.Cart.CartItemAdd:input_type -> route.cart.pkg.api.v1.CartItemAddRequest
	2,  // 2: route.cart.pkg.api.v1.Cart.CartItemDelete:input_type -> route.cart.pkg.api.v1.CartItemDeleteRequest
	4,  // 3: route.cart.pkg.api.v1.Cart.CartList:input_type -> route.cart.pkg.api.v1.CartListRequest
	6,  // 4: route.cart.pkg.api.v1.Cart.CartClear:input_type -> route.cart.pkg.api.v1.CartClearRequest
	8,  // 5: route.cart.pkg.api.v1.Cart.CartCheckout:input_type -> route.cart.pkg.api.v1.CartCheckoutRequest
	1,  // 6: route.cart.pkg.api.v1.Cart.CartItemAdd:output_type -> route.cart.pkg.api.v1.CartItemAddResponse
	3,  // 7: route.cart.pkg.api.v1.Cart.CartItemDelete:output_type -> route.cart.pkg.api.v1.CartItemDeleteResponse
	5,  // 8: route.cart.pkg.api.v1.Cart.CartList:output_type -> route.cart.pkg.api.v1.CartListResponse
	7,  // 9: route.cart.pkg.api.v1.Cart.CartClear:output_type -> route.cart.pkg.api.v1.CartClearResponse
	9,  // 10: route.cart.pkg.api.v1.Cart.CartCheckout:output_type -> route.cart.pkg.api.v1.CartCheckoutResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_cart_service_proto_init() }
func file_api_v1_cart_service_proto_init() {
	if File_api_v1_cart_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_cart_service_proto_rawDesc), len(file_api_v1_cart_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_cart_service_proto_goTypes,
		DependencyIndexes: file_api_v1_cart_service_proto_depIdxs,
		MessageInfos:      file_api_v1_cart_service_proto_msgTypes,
	}.Build()
	File_api_v1_cart_service_proto = out.File
	file_api_v1_cart_service_proto_goTypes = nil
	file_api_v1_cart_service_proto_depIdxs = nil
}
